global:
  imagePullPolicy: Always
  imagePullSecrets:               
    - registry-credentials
  ultihashSecret:
    name: ultihash
    key: license
  logLevel: INFO
  telemetryExportInterval: 30000

recovery:
  nodeSelector:
    purpose: 10TB
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ultihash-testing"
      effect: "NoSchedule"

etcd:
  replicaCount: 1
  nodeSelector:
    purpose: 10TB
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ultihash-testing"
      effect: "NoSchedule"
  persistence:
    size: 8Gi
    storageClass: ebs-csi-gp3-normal

entrypoint:
  replicas: 1
  nodeSelector:
    purpose: 10TB
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ultihash-testing"
      effect: "NoSchedule"

  ingress:
    host: 
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-body-size: "0"

storage:
  replicas: 1
  storageClass: ebs-csi-gp3-optimized 
  storageSize: 10Ti            
  nodeSelector:
    purpose: 10TB
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ultihash-testing"
      effect: "NoSchedule"

deduplicator:
  replicas: 1
  storageClass: ebs-csi-gp3-normal
  storageSize: 300Gi
  nodeSelector:
    purpose: 10TB
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ultihash-testing"
      effect: "NoSchedule"

database:
  primary:
    nodeSelector:
      purpose: 10TB
    tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ultihash-testing"
      effect: "NoSchedule"

    persistence:
      storageClass: ebs-csi-gp3-normal 
      size: 300Gi

databaseInit:
  nodeSelector:
    purpose: 10TB
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ultihash-testing"
      effect: "NoSchedule"

collector:
  nodeSelector:
    purpose: 10TB
  tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "ultihash-testing"
      effect: "NoSchedule"
  extraEnvs:
  - name: UH_POD_IP
    valueFrom:
      fieldRef:
        fieldPath: status.podIP
  - name: UH_NODE_IP
    valueFrom:
      fieldRef:
        fieldPath: status.hostIP
  - name: UH_EXPORTER_TOKEN
    valueFrom:
      secretKeyRef:
        name: ultihash
        key: token
  presets:
    kubeletMetrics:              
      enabled: false           
  config:                         
    exporters:
      otlphttp/uptrace:
        endpoint: https://collector.ultihash.io
        headers:
          uptrace-dsn: https://${env:UH_EXPORTER_TOKEN}@collector.ultihash.io
    receivers:
      prometheus: null
      kubeletstats: null
    service:
      pipelines:
        metrics:
          receivers:
            - otlp

exporter:
  enabled: false
                   