# Copyright 2026 UltiHash Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: ultihash-node
spec:
  disruption:
    consolidateAfter: 1m
    consolidationPolicy: WhenEmpty
  template:
    metadata:
      labels:
        purpose: 10TB
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: ultihash-testing
      requirements:
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
      - key: kubernetes.io/arch
        operator: In
        values:
        - arm64
      - key: node.kubernetes.io/instance-type
        operator: In
        values:
        - r8g.4xlarge
      taints:
      - effect: NoSchedule
        key: purpose
        value: ultihash-testing
