apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: ultihash-testing
spec:
  amiFamily: Bottlerocket
  role: ${node_registration_role}
  subnetSelectorTerms:
    - tags:
        Name: "ultihash-test-private-eu-central-1b"
  securityGroupSelectorTerms:
    - tags:
        Name: "ultihash-test-node"
  tags:
    created_by: karpenter
    purpose: ultihash-testing
  detailedMonitoring: false
  associatePublicIPAddress: false