apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: ultihash-testing
spec:
  amiSelectorTerms:
    - alias: bottlerocket@v1.32.0
  role: ${node_registration_role}
  subnetSelectorTerms:
    - tags:
        Name: "ultihash-test-private-eu-central-1b"
  securityGroupSelectorTerms:
    - tags:
        Name: "ultihash-test-node"
  tags:
    created_by: karpenter
    purpose: ultihash-testing
  detailedMonitoring: false
  associatePublicIPAddress: false